package md.reactive_messaging.reactive;

public enum Reconnect
{
    @Deprecated
    RECONNECT,
    CREATING_CONTEXT_FAILED,
    SETTING_EXCEPTION_LISTENER_FAILED,
    CREATING_QUEUE_FAILED,
    CREATING_CONSUMER_FAILED,
    STARTING_CONTEXT,
    SETTING_MESSAGE_LISTENER,
    EXCEPTION_IN_CONTEXT_HEARD
}
